// Mocks generated by Mockito 5.4.6 from annotations
// in lumeo/test/presentation/blocs/video_list_bloc/video_list_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:lumeo/domain/entities/video_file.dart' as _i5;
import 'package:lumeo/domain/repositories/video_repository.dart' as _i2;
import 'package:lumeo/domain/usecases/get_videos.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeVideoRepository_0 extends _i1.SmartFake
    implements _i2.VideoRepository {
  _FakeVideoRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetVideos].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetVideos extends _i1.Mock implements _i3.GetVideos {
  MockGetVideos() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.VideoRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeVideoRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.VideoRepository);

  @override
  _i4.Future<List<_i5.VideoFile>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<List<_i5.VideoFile>>.value(<_i5.VideoFile>[]),
      ) as _i4.Future<List<_i5.VideoFile>>);
}
