name: awesome_video_player
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  video_player: ^2.8.6
  provider: ^6.1.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.1
  shared_preferences: ^2.2.3

  flutter_bloc: ^8.1.5
  equatable: ^2.0.5

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  bloc_test: ^9.1.7 # Added for BLoC testing

flutter:
  uses-material-design: true
